digapp2:
  image: digmemex/digapp:2.0.5
  ports:
    - "8080"
  volumes:
    - ./logs/digapp:/var/log
  environment:
    ELASTIC_INDEX: 'dig-ht-2015-oct-nov-02-images-03'
    ELASTIC_CONFIG: '{"host": "http://digappdev.dig.isi.edu:8080"}'
    NODE_ENV: 'production'

nginx-digapp2:
  image: nginx
  links:
    - digapp2:digapp
  ports:
    - "8080:80"
  volumes:
    - ./conf/nginx/.htpasswd:/etc/nginx/.htpasswd
    - ./conf/nginx_sites_enabled/dig:/etc/nginx/conf.d/default.conf
    - ./logs/nginx:/var/log/nginx
    - ./logs/digapp:/var/log/diglogs
