version: '2'
services:
  smtp:
    image: namshi/smtp
  notifyapp:
    image: digmemex/notifyapp:version
    environment:
      DIG_SUPPORT_EMAIL_ADDRESS: dig-support@nextcentury.com
      DIG_URL: url
      ES_AUTH: user:pass
      ES_HOST: hostname
      ES_PORT: port
      ES_PROTOCOL: http
      DATA_INDEX: index
    volumes:
      - /tmp/dig_alerts_app:/var/log
